services:
    app:
        hostname: dc
        ports:
            - 5173:5173
        image: node:24-trixie-slim
        command: sleep infinity
        env_file:
            - .env
        volumes:
            - ../..:/workspaces:cached
            - .zshrc:/root/.zshrc:cached
            - ~/.config:/root/.config:cached
            - ~/.ssh:/root/.ssh:cached
